language: java
jdk: oraclejdk8
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - git clone -b fit3d-feature https://github.com/cleberecht/singa.git
  - cd singa/singa-all
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd  ../../mmm-all

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
