language: java
jdk: oraclejdk8
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - git clone -b alignment-algorithms https://github.com/cleberecht/singa.git
  - cd singa/singa-all
  - mvn clean install -DskipTests=true
  - cd  ../../mmm-all

install: mvn clean install -DskipTests=true
